# Generated by Django 4.2.5 on 2023-09-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('produto', models.CharField(max_length=10)),
                ('valor', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
